export POSTGRES_USERNAME=yourpostgrescredential
export POSTGRES_PASSWORD=yourpostgrescredential
export POSTGRES_DATABASE=yourpostgrescredential
export POSTGRES_HOST=yourpostgrescredential
 
export AWS_REGION=yourawscredential
export AWS_MEDIA_BUCKET=yourawsS3credential
